### ISSUE TITLE
Check into non admin users trying to update their officer information

### ISSUE THREAD

**Issue by kcin1018** [cincyultimate/website#44]
When Gorman tried to update his president image an error occurred.  Investigate and see if there is a problem.

**Comment by kcin1018** [comment]
[2016-08-30 08:13:30] prod.ERROR: Symfony\Component\Debug\Exception\FatalThrowableError: Class 'Cupa\Http\Requests\Auth' not found in /www/cupa/app/Http/Requests/BoardAddEditRequest.php:16
Stack trace:
#0 [internal function]: Cupa\Http\Requests\BoardAddEditRequest->authorize()
#1 /www/cupa/bootstrap/cache/compiled.php(1257): call_user_func_array(Array, Array)
#2 /www/cupa/bootstrap/cache/compiled.php(5606): Illuminate\Container\Container->call(Array)
#3 /www/cupa/bootstrap/cache/compiled.php(5514): Illuminate\Foundation\Http\FormRequest->passesAuthorization()
#4 /www/cupa/bootstrap/cache/compiled.php(5695): Illuminate\Foundation\Http\FormRequest->validate()
#5 /www/cupa/bootstrap/cache/compiled.php(1494): Illuminate\Foundation\Providers\FoundationServiceProvider->Illuminate\Foundation\Providers\{closure}(Object(Cupa\Http\Requests\BoardAddEditRequest), Object(Illuminate\Foundation\Application))
#6 /www/cupa/bootstrap/cache/compiled.php(1479): Illuminate\Container\Container->fireCallbackArray(Object(Cupa\Http\Requests\BoardAddEditRequest), Array)
#7 /www/cupa/bootstrap/cache/compiled.php(1319): Illuminate\Container\Container->fireResolvingCallbacks('Cupa\\Http\\Reque...', Object(Cupa\Http\Requests\BoardAddEditRequest))
#8 /www/cupa/bootstrap/cache/compiled.php(1874): Illuminate\Container\Container->make('Cupa\\Http\\Reque...', Array)
#9 /www/cupa/bootstrap/cache/compiled.php(7940): Illuminate\Foundation\Application->make('Cupa\\Http\\Reque...')
#10 /www/cupa/bootstrap/cache/compiled.php(7929): Illuminate\Routing\ControllerDispatcher->transformDependency(Object(ReflectionParameter), Array, Array)
#11 /www/cupa/bootstrap/cache/compiled.php(7923): Illuminate\Routing\ControllerDispatcher->resolveMethodDependencies(Array, Object(ReflectionMethod))
#12 /www/cupa/bootstrap/cache/compiled.php(9485): Illuminate\Routing\ControllerDispatcher->resolveClassMethodDependencies(Array, Object(Cupa\Http\Controllers\AboutController), 'postBoardEdit')
#13 /www/cupa/bootstrap/cache/compiled.php(9466): Illuminate\Routing\ControllerDispatcher->call(Object(Cupa\Http\Controllers\AboutController), Object(Illuminate\Routing\Route), 'postBoardEdit')
#14 [internal function]: Illuminate\Routing\ControllerDispatcher->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#15 /www/cupa/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#16 [internal function]: Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#17 /www/cupa/bootstrap/cache/compiled.php(9948): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#18 /www/cupa/bootstrap/cache/compiled.php(9467): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#19 /www/cupa/bootstrap/cache/compiled.php(9454): Illuminate\Routing\ControllerDispatcher->callWithinStack(Object(Cupa\Http\Controllers\AboutController), Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'postBoardEdit')
#20 /www/cupa/bootstrap/cache/compiled.php(8524): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'Cupa\\Http\\Contr...', 'postBoardEdit')
#21 /www/cupa/bootstrap/cache/compiled.php(8511): Illuminate\Routing\Route->runController(Object(Illuminate\Http\Request))
#22 /www/cupa/bootstrap/cache/compiled.php(8225): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#23 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#24 /www/cupa/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#25 [internal function]: Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#26 /www/cupa/bootstrap/cache/compiled.php(9948): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#27 /www/cupa/bootstrap/cache/compiled.php(8226): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#28 /www/cupa/bootstrap/cache/compiled.php(8217): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#29 /www/cupa/bootstrap/cache/compiled.php(8207): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#30 /www/cupa/bootstrap/cache/compiled.php(2419): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#31 [internal function]: Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#32 /www/cupa/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#33 /www/cupa/app/Http/Middleware/Setup.php(36): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#34 [internal function]: Cupa\Http\Middleware\Setup->handle(Object(Illuminate\Http\Request), Object(Closure))
#35 /www/cupa/bootstrap/cache/compiled.php(9963): call_user_func_array(Array, Array)
#36 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#37 /www/cupa/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#38 /www/cupa/bootstrap/cache/compiled.php(3225): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#39 [internal function]: Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#40 /www/cupa/bootstrap/cache/compiled.php(9963): call_user_func_array(Array, Array)
#41 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#42 /www/cupa/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#43 /www/cupa/bootstrap/cache/compiled.php(13474): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#44 [internal function]: Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#45 /www/cupa/bootstrap/cache/compiled.php(9963): call_user_func_array(Array, Array)
#46 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#47 /www/cupa/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#48 /www/cupa/bootstrap/cache/compiled.php(11964): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#49 [internal function]: Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#50 /www/cupa/bootstrap/cache/compiled.php(9963): call_user_func_array(Array, Array)
#51 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#52 /www/cupa/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#53 /www/cupa/bootstrap/cache/compiled.php(13213): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#54 [internal function]: Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#55 /www/cupa/bootstrap/cache/compiled.php(9963): call_user_func_array(Array, Array)
#56 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#57 /www/cupa/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#58 /www/cupa/bootstrap/cache/compiled.php(13150): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#59 [internal function]: Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#60 /www/cupa/bootstrap/cache/compiled.php(9963): call_user_func_array(Array, Array)
#61 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#62 /www/cupa/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#63 /www/cupa/bootstrap/cache/compiled.php(3286): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#64 [internal function]: Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#65 /www/cupa/bootstrap/cache/compiled.php(9963): call_user_func_array(Array, Array)
#66 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#67 /www/cupa/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#68 [internal function]: Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#69 /www/cupa/bootstrap/cache/compiled.php(9948): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#70 /www/cupa/bootstrap/cache/compiled.php(2366): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#71 /www/cupa/bootstrap/cache/compiled.php(2350): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#72 /www/cupa/public/index.php(52): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#73 {main}

**Comment by kcin1018** [comment]
fixed with 1c90ba5ae950ac9ca27f1f9ef6791f9617d3f5e3
